---
development:
  layout: layout.html
  view_dir: views
  path_prefix: /admin/
  turk_path_prefix: /turk/
  turk_sandbox: true
  turk_reward: 0.25
  turk_hit_type_id: ""
  aws_access_key: ""
  aws_secret_access_key: ""
  base_url: "http://localhost:3000/"
